# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Sankalp Prabhakar
tagline:          ''
description:      'Passionate about applying machine learning to solve real-world problems!'
url:              https://sankalp-prabhakar.github.io
baseurl:          /

author:
  name:           'Sankalp Prabhakar'
  url:            https://twitter.com/iam_sankalp

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sankalp-prabhakar/sankalp-prabhakar.github.io

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet